language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-26.0.2
    - android-23
    - android-21
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - '.+'

script:
  - ./gradlew :visearch-android:clean :visearch-android:test
